//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

	public static class genFunc
	{


		public static bool inRange (float val, float comp, float tol)
		{
			return comp - tol < val && val < comp + tol;
		}
	}


