//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public enum enPlayer
{
	yellow = 0,
	green = 1
}

public enum enAction
{
	grabPopCorn,
	grabLightBulb,
	clap
}

public enum enRelease
{
	front,
	popcorn
}

public static class gVar
{
	public const string tagStand = "Stand";
	public const string tagPopCorn = "PopCorn";
	public const string tagLightBulb = "LightBulb";
	public const string tagGlass = "Glass";
	public const string tagGlassOut = "GlassOut";
	public const string tagScore = "Score";
	public const string tagPlayer = "Player";

	public const float standHeight = 0.07f;

	public const float minSpeedChoc = 0.1f;
	public const float timeBetweenChoc = 2f;

	public const string prefKeyboard = "keyLay";
	public const string prefkeyNumLock = "keyNumLock";

	public static KeyCode[] keyAction1 = new KeyCode[]{KeyCode.Q, KeyCode.Keypad7};
	public static KeyCode[] keyUp = new KeyCode[]{KeyCode.W, KeyCode.Keypad8};
	public static KeyCode[] keyDown = new KeyCode[]{KeyCode.S, KeyCode.Keypad5};
	public static KeyCode[] keyLeft = new KeyCode[]{KeyCode.A, KeyCode.Keypad4};
	public static KeyCode[] keyRight = new KeyCode[]{KeyCode.D, KeyCode.Keypad6};
	public static KeyCode[] keyRelease = new KeyCode[]{KeyCode.E, KeyCode.Keypad9};
	public static KeyCode[] keyDeposeLightBulb = new KeyCode[]{KeyCode.Y, KeyCode.Keypad1};
	public static KeyCode[] keySpeedSlow = new KeyCode[]{KeyCode.X, KeyCode.Keypad2};
	public static KeyCode keyStart = KeyCode.Space;
	public static KeyCode keyHelp = KeyCode.H;
	public static KeyCode keyExit = KeyCode.F4;
	public static KeyCode keyCancel = KeyCode.Escape;

}


